export const UserActionTypes = {
	GET_AUTHORIZATION_CODE:'GET_AUTHORIZATION_CODE',
	SPOTIFY_AUTH_START:'SPOTIFY_AUTH_START',
	SIGN_IN_SUCCESS:'SIGN_IN_SUCCESS',
	SIGN_IN_FAILURE:'SIGN_IN_FAILURE',
	SIGN_OUT_SUCCESS:'SIGN_OUT_SUCCESS',
	GET_USER_PROFILE_SUCCESS:'GET_USER_PROFILE_SUCCESS',
	GET_USER_PROFILE_FAILURE:'GET_USER_PROFILE_FAILURE',
	GET_NEW_RELEASES_SUCCESS:'GET_NEW_RELEASES_SUCCESS',
	GET_NEW_RELEASES_FAILURE:'GET_NEW_RELEASES_FAILURE',
	GET_FIREBASE_LIBRARY:'GET_FIREBASE_LIBRARY',
	SAVE_TO_LIBRARY:'SAVE_TO_LIBRARY',
	REMOVE_FROM_LIBRARY:'REMOVE_FROM_LIBRARY',
	UPDATE_LIBRARY_SUCCESS:'UPDATE_LIBRARY_SUCCESS',
	SEARCH_ALBUM_START:'SEARCH_ALBUM_START',
	SEARCH_ALBUM_SUCCESS:'SEARCH_ALBUM_SUCCESS',
	SEARCH_ALBUM_FAILURE:'SEARCH_ALBUM_FAILURE',
	SET_ERROR_MESSAGE:'SET_ERROR_MESSAGE'
};

export default UserActionTypes;